// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Restaurant.Persistence.Context;

#nullable disable

namespace Restaurant.Persistence.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizadopor");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creadopor");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion");

                    b.Property<int?>("MozoId")
                        .HasColumnType("integer")
                        .HasColumnName("mozoid");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("integer")
                        .HasColumnName("numeromesa");

                    b.HasKey("Id")
                        .HasName("pk_mesas");

                    b.HasIndex("MozoId")
                        .HasDatabaseName("ix_mesas_mozoid");

                    b.ToTable("mesas");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizadopor");

                    b.Property<string>("ClienteNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("clientenombre");

                    b.Property<string>("ClienteTelefono")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("clientetelefono");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creadopor");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaentrega");

                    b.Property<int?>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesaid");

                    b.Property<int?>("MozoId")
                        .HasColumnType("integer")
                        .HasColumnName("mozoid");

                    b.Property<int?>("RepartidorId")
                        .HasColumnType("integer")
                        .HasColumnName("repartidorid");

                    b.Property<string>("TipoPedido")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipopedido");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("MesaId")
                        .HasDatabaseName("ix_pedidos_mesaid");

                    b.HasIndex("MozoId")
                        .HasDatabaseName("ix_pedidos_mozoid");

                    b.HasIndex("RepartidorId")
                        .HasDatabaseName("ix_pedidos_repartidorid");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizadopor");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creadopor");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionCompleta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccioncompleta");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombrecliente");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedidoid");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("referencia");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("pk_direcciones");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasDatabaseName("ix_direcciones_pedidoid");

                    b.ToTable("direcciones");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedidoid");

                    b.Property<int>("PlatoId")
                        .HasColumnType("integer")
                        .HasColumnName("platoid");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_pedidodetalles");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedidodetalles_pedidoid");

                    b.HasIndex("PlatoId")
                        .HasDatabaseName("ix_pedidodetalles_platoid");

                    b.ToTable("pedidodetalles");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Plato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualizadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("actualizadopor");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoriaid");

                    b.Property<int?>("CreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("creadopor");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean")
                        .HasColumnName("eliminado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaactualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id")
                        .HasName("pk_platos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_platos_categoriaid");

                    b.ToTable("platos");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_nombre");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pinhash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioid");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rolid");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuarioroles");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuarioroles_rolid");

                    b.ToTable("usuarioroles");
                });

            modelBuilder.Entity("Mesa", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Usuario", "Mozo")
                        .WithMany()
                        .HasForeignKey("MozoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_mesas_usuarios_mozoid");

                    b.Navigation("Mozo");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.HasOne("Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_mesas_mesaid");

                    b.HasOne("Restaurant.Domain.Entities.Usuario", "Mozo")
                        .WithMany()
                        .HasForeignKey("MozoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_usuarios_mozoid");

                    b.HasOne("Restaurant.Domain.Entities.Usuario", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pedidos_usuarios_repartidorid");

                    b.Navigation("Mesa");

                    b.Navigation("Mozo");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Direccion", b =>
                {
                    b.HasOne("Pedido", "Pedido")
                        .WithOne("Direccion")
                        .HasForeignKey("Restaurant.Domain.Entities.Direccion", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direcciones_pedidos_pedidoid");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.PedidoDetalle", b =>
                {
                    b.HasOne("Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedidodetalles_pedidos_pedidoid");

                    b.HasOne("Restaurant.Domain.Entities.Plato", "Plato")
                        .WithMany()
                        .HasForeignKey("PlatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidodetalles_platos_platoid");

                    b.Navigation("Pedido");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Plato", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Platos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_platos_categorias_categoriaid");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Restaurant.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarioroles_roles_rolid");

                    b.HasOne("Restaurant.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarioroles_usuarios_usuarioid");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Restaurant.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
